GET http://localhost:8080/employee/add?firstName=La&lastName=Alikritskikkkh
###
GET http://localhost:8080/employee/add?firstName=La&lastName=Alikritskikkk
###
GET http://localhost:8080/employee/add?firstName=La&lastName=Alikritskikkkh

